**Assignment: Section 7. Data Collection**

This notebook walks through the workflow for:

1. Loading a dataset from a CSV file
2. Inserting the data into a database table (manual insertion step)
3. Loading the data back from the database into a pandas DataFrame
4. Verifying the shape and columns
5. Saving the data as an Excel file
6. Saving the data as a Parquet file

> Note: This notebook assumes that you **already created a database and table**, and that you **inserted the CSV data into that table** using a DB tool (e.g., DBeaver, pgAdmin).

In [1]:
# install required libraries
%pip install SQLAlchemy psycopg2-binary pandas openpyxl pyarrow -q

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from sqlalchemy import create_engine

**Load dataset from CSV**

In [3]:
# 1) Load dataset from CSV
CSV_FILE = "insurance.csv"
df_csv = pd.read_csv(CSV_FILE)

print("Loaded from CSV")
print("Shape:", df_csv.shape)
print("Columns:", list(df_csv.columns))
display(df_csv.head())

Loaded from CSV
Shape: (1338, 7)
Columns: ['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## 2) Database connection

Here we create a SQLAlchemy engine that connects to our PostgreSQL database using a connection string.

Make sure to update the connection string with your own user, password, host, port, and database name if needed.

In [4]:
# 2) Database connection
connection_string = "postgresql://test_user:test_password@localhost:5432/ml_db"
engine = create_engine(connection_string)

## 3) Manual insertion step (recommended)

This step is done **outside** of the notebook, using a database tool such as DBeaver or pgAdmin:

1. Create a table in your database (e.g., in a schema like `datasets`).
2. Import/insert the CSV data into that table using the tool's import wizard.
3. Once the data is inserted, come back to this notebook to continue.

Update the table name below so that it matches the table you created.

In [5]:
# Update these to match your DB
TABLE_NAME = "datasets.my_table"   # example: datasets.diabetes
QUERY = f"SELECT * FROM {TABLE_NAME}"

## 4) Load data back from the database

Now we read the data from the database table into a pandas DataFrame using `pd.read_sql`.

In [ ]:
# 4) Load data back from DB
df_db = pd.read_sql(sql=QUERY, con=engine)


print("\nLoaded from Database")
print("Shape:", df_db.shape)
print("Columns:", list(df_db.columns))
display(df_db.head())

Loaded from Database
Shape: (1338, 7)
Columns: ['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## 5) Verify shape and columns

We compare the shape of the original CSV DataFrame and the DataFrame loaded from the database, and we also compute how many columns they have in common.

In [8]:
# 5) Verify shape and columns
print("\nQuick verification")
print("CSV shape:", df_csv.shape)
print("DB shape :", df_db.shape)

common_cols = set(df_csv.columns).intersection(set(df_db.columns))
print("Common columns count:", len(common_cols))

Quick verification
CSV shape: (1338, 7)
DB shape : (1338, 7)
Common columns count: 7

## 6) Save as Excel

We save the DataFrame loaded from the database to an Excel file.

In [9]:
# 6) Save as Excel
EXCEL_FILE = "dataset_from_db.xlsx"
df_db.to_excel(EXCEL_FILE, index=False)
print("\nSaved Excel file:", EXCEL_FILE)

Saved Excel file: dataset_from_db.xlsx

## 7) Save as Parquet

Finally, we save the same DataFrame to a Parquet file.

In [10]:
# 7) Save as Parquet
PARQUET_FILE = "dataset_from_db.parquet"
df_db.to_parquet(PARQUET_FILE, index=False)
print("Saved Parquet file:", PARQUET_FILE)

print("\nDone.")

Saved Parquet file: dataset_from_db.parquet

Done.